### ISSUE TITLE
Implement finale event type

### ISSUE THREAD

**Issue by deSagaz** [deSagaz/java-sparrow#15]
Event that can run at the end of a level. Takes final score and is then able to determine whether the level was completed.

**Comment by Kelly-Griffioen** [comment]
The todo list we made said we needed a possibility to go to the next sequence, but I was wondering how high the priority is on that, because if we want to make that work we need to, besides get the next scene if it exists, also check whether the user has enough points for that next scene and act accordingly.

**Comment by deSagaz** [comment]
True... Let's skip that for now - it is easily implemented later on (with checks) later on as addition.
